embedding_model_name: "all-MiniLM-L12-v2"
rag_llm_model_name: "meta-llama/Llama-3.2-1B-Instruct"
max_token_limit: 4096
chunk_overlap: 200
chromadb_collection_name: tech_jobs
query_prompt: >
  Identify the top 3 job roles or careers for gig workers or freelancers in {current_month} {current_year}. 
  For each job role, list the top 5 most in-demand skills required to succeed. Provide your response in a structured 
  format. Keep your response concise and aligned with the specified format.
